[package]
name = "gsim"
version = "0.1.0"
edition = "2021"
authors = ["Mathis Rech"]
license = "MIT"
description = "High speed digital logic simulation"
rust-version = "1.70"

[lib]
crate-type = ["lib", "cdylib"]

[[bench]]
name = "sim"
harness = false

[features]
yosys-import = ["serde", "dep:serde_json", "dep:indexmap"]

[dependencies]
rayon = "1.6"
static_assertions = "1.1"
bounded-integer = { version = "0.5", features = ["types"] }
smallvec = { version = "1.10", features = ["serde", "union", "const_generics"] }
num_cpus = "1.15"
sync-unsafe-cell = "0.1.1"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
indexmap = { version = "2.0.0", features = ["serde"], optional = true }

[dev-dependencies]
criterion = "0.4"
rand = "0.8"
