[package]
name = "gsim"
version = "0.1.0"
edition = "2021"
authors = [ "Mathis Rech" ]
license = "MIT"
description = "Circuit simulator"

[lib]
crate-type = [ "lib", "cdylib" ]

[dependencies]
rayon = "1.5"
ahash = "0.7"
