[package]
name = "gsim"
version = "0.1.0"
edition = "2021"
authors = ["Mathis Rech"]
license = "MIT"
description = "High speed digital logic simulation"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
rayon = "1.6"
static_assertions = "1.1"
bounded-integer = { version = "0.5", features = ["types"] }
smallvec = "1.10"
